### ISSUE TITLE
Instruction in README.md does not work

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/communitheme-snap-helpers#10]
Hi, I was trying to run: `snap install communitheme-set-default --classic` as instructed in https://github.com/ubuntu/communitheme-snap-helpers/blob/master/README.md but I get error:
`error: snap "communitheme-set-default" not found`

I'm on Ubuntu 18.04 and installed the communitheme as a snap from the Software Center.

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting!

`communitheme-set-default` isn't released yet. I removed the text from the readme.
